apiVersion: v1
kind: Pod
metadata:
  name: secure-pod-2
  namespace: audit-zone
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
