apiVersion: v1
kind: Pod
metadata:
  name: secure-pod-3
  namespace: audit-zone
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: alpine
      image: alpine
      command: ["sleep", "3600"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 3000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
